##############################################################################################
## SMT-FMC-R Constraints file
##############################################################################################

##############################################################################################
## DIOs
#Pins
set_property PACKAGE_PIN W11 [get_ports {dio_tri_io[18]}]
set_property PACKAGE_PIN V11 [get_ports {dio_tri_io[17]}]
set_property PACKAGE_PIN Y12 [get_ports {dio_tri_io[15]}]
set_property PACKAGE_PIN V14 [get_ports {dio_tri_io[14]}]
set_property PACKAGE_PIN V13 [get_ports {dio_tri_io[13]}]
set_property PACKAGE_PIN U14 [get_ports {dio_tri_io[12]}]
set_property PACKAGE_PIN U13 [get_ports {dio_tri_io[11]}]
set_property PACKAGE_PIN G8 [get_ports {dio_tri_io[0]}]
set_property PACKAGE_PIN G7 [get_ports {dio_tri_io[1]}]
set_property PACKAGE_PIN B7 [get_ports {dio_tri_io[2]}]
set_property PACKAGE_PIN B6 [get_ports {dio_tri_io[3]}]
set_property PACKAGE_PIN G2 [get_ports {dio_tri_io[5]}]
set_property PACKAGE_PIN G3 [get_ports {dio_tri_io[6]}]
set_property PACKAGE_PIN F4 [get_ports {dio_tri_io[7]}]
set_property PACKAGE_PIN G4 [get_ports {dio_tri_io[8]}]
set_property PACKAGE_PIN A4 [get_ports {dio_tri_io[9]}]
set_property PACKAGE_PIN A5 [get_ports {dio_tri_io[10]}]
set_property PACKAGE_PIN F1 [get_ports {dio_tri_io[4]}]
#IO Standards
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dio_tri_io[0]}]
##############################################################################################

##############################################################################################
##GPIOs
#Pins
set_property PACKAGE_PIN AA15 [get_ports {gpio_tri_io[8]}]
set_property PACKAGE_PIN AA14 [get_ports {gpio_tri_io[9]}]
set_property PACKAGE_PIN AB16 [get_ports {gpio_tri_io[14]}]
set_property PACKAGE_PIN AB17 [get_ports {gpio_tri_io[15]}]
set_property PACKAGE_PIN Y19 [get_ports {gpio_tri_io[24]}]
set_property PACKAGE_PIN Y18 [get_ports {gpio_tri_io[25]}]
set_property PACKAGE_PIN AA12 [get_ports {gpio_tri_io[10]}]
set_property PACKAGE_PIN AB12 [get_ports {gpio_tri_io[11]}]
set_property PACKAGE_PIN V16 [get_ports {gpio_tri_io[0]}]
set_property PACKAGE_PIN W16 [get_ports {gpio_tri_io[1]}]
set_property PACKAGE_PIN Y17 [get_ports {gpio_tri_io[2]}]
set_property PACKAGE_PIN W17 [get_ports {gpio_tri_io[3]}]
set_property PACKAGE_PIN E3 [get_ports {gpio_tri_io[12]}]
set_property PACKAGE_PIN E4 [get_ports {gpio_tri_io[13]}]
set_property PACKAGE_PIN C6 [get_ports {gpio_tri_io[4]}]
set_property PACKAGE_PIN C5 [get_ports {gpio_tri_io[5]}]
set_property PACKAGE_PIN H3 [get_ports {gpio_tri_io[6]}]
set_property PACKAGE_PIN H4 [get_ports {gpio_tri_io[7]}]
set_property PACKAGE_PIN C8 [get_ports {gpio_tri_io[20]}]
set_property PACKAGE_PIN B8 [get_ports {gpio_tri_io[21]}]
set_property PACKAGE_PIN H6 [get_ports {gpio_tri_io[27]}]
set_property PACKAGE_PIN D5 [get_ports {gpio_tri_io[16]}]
set_property PACKAGE_PIN Y13 [get_ports {dio_tri_io[16]}]
set_property PACKAGE_PIN C4 [get_ports {gpio_tri_io[17]}]
set_property PACKAGE_PIN E2 [get_ports {gpio_tri_io[18]}]
set_property PACKAGE_PIN D2 [get_ports {gpio_tri_io[19]}]
set_property PACKAGE_PIN H5 [get_ports {gpio_tri_io[26]}]
set_property PACKAGE_PIN H1 [get_ports {gpio_tri_io[22]}]
set_property PACKAGE_PIN G1 [get_ports {gpio_tri_io[23]}]
#IO Standards
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_tri_io[0]}]
##############################################################################################

##############################################################################################
## UARTs (ADCs)
#Pins
set_property PACKAGE_PIN A6 [get_ports UART_3_rxd]
set_property PACKAGE_PIN F2 [get_ports UART_3_txd]
set_property PACKAGE_PIN A7 [get_ports {uart_rq_tri_io[2]}]
set_property PACKAGE_PIN U11 [get_ports UART_2_rxd]
set_property PACKAGE_PIN AB14 [get_ports UART_2_txd]
set_property PACKAGE_PIN U12 [get_ports {uart_rq_tri_io[1]}]
set_property PACKAGE_PIN R17 [get_ports UART_1_rxd]
set_property PACKAGE_PIN T17 [get_ports UART_1_txd]
set_property PACKAGE_PIN AB13 [get_ports {uart_rq_tri_io[0]}]
#IO Standards
set_property IOSTANDARD LVCMOS18 [get_ports UART_3_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports UART_3_txd]
set_property IOSTANDARD LVCMOS18 [get_ports {uart_rq_tri_io[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports UART_2_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports UART_2_txd]
set_property IOSTANDARD LVCMOS18 [get_ports {uart_rq_tri_io[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports UART_1_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports UART_1_txd]
set_property IOSTANDARD LVCMOS18 [get_ports {uart_rq_tri_io[0]}]

##############################################################################################

